<br> <br> <br> <br>
<img src="<?php echo $this->city_data->imag_path;?>" style="width: 100%; height: 60%" >
<br>
<h1 class="section-title" style="text-align: center">Welcome To <?php echo $this->city_data->name;?></h1>

<h4 style="text-align: center"><?php echo $this->city_data->description;?> </h4>
<br>

<h4><?php echo "Sights in ".$this->city_data->name?></h4>


<hr>

<div class="row">

	<?php foreach($this->city_locations as $key=>$value)
			{
				?>

	<div class="col-md-4 col-sm-6">

		<div class="product-item">

			<div class="item-thumb">

				<div class="overlay">

					<div class="overlay-inner">


					</div>
				</div>
				 <label><?php echo $value['name'];?></label>
				<img style='width:400px; ' src=" <?php echo $value['imag_path']?> "alt='No image was found'>

			</div>
		</div>

	</div>
	<?php
			}

		?>

</div>


<div id="map"></div>


<br>
<h1 class="section-title" style="text-align: center">Recent Articles </h1>

	<?php


foreach ($this->paginator as $article) {

	?>

<h2 style="display: inline; padding-left: 140px;">  <?php echo  $article->title;?> </h2>

<h4 style="padding-left:140px; width: 80%;  "><pre ><?php echo  substr($article->content, 0, 50)." .... "; ?><a href="<?php echo"/article/show/article_id/".$article->id;?>">Read More</a> </pre></h4>
	<hr>
<?php


}

echo '<h3>'. $this->paginator. '</h3>';

?>






<script>

	function initMap() {
		var mapDiv = document.getElementById('map');
		var map = new google.maps.Map(mapDiv,{
			center: {lat: <?php echo $this->city_data->latitude;?> , lng: <?php echo $this->city_data->longitude;?>},
			zoom: 11
		});


	}



</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8qj-3E6nRcvPyJP9DwpAZ3Xr_iSq_ot8&callback=initMap" async defer></script>
