<?php
$article_id = $this->article_id;

$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();

if (!empty($sessionRead)) {

    $name = $sessionRead->name;
    $id = $sessionRead->id;
    $image_path = $sessionRead->imag_path;
    $read_only="false";
}
else{
    $image_path="";
    $read_only = "true";
    $name="";
    $id="";
}
?>
<br> <br> <br>


<h1 class="section-title" style="text-align: center"><?php echo $this->article->title;?></h1>

<center><img style="width: 90%; " align="middle" src="<?php echo $this->article->image_path;?> " alt="No Image For This Article"></center>
<h2 style="padding-left: 123px; width: 90%"><pre > <?php echo $this->article->content;?></pre></h2>

<div id="comments-container" style="width: 80%; font-size: 20px; padding-left: 280px;"></div>
<script type="text/javascript" src="/resources/js/jquery-comments.js"></script>
<script>

    $("#comments-container").comments({
        profilePictureURL: 'http://travel.com/<?php echo $image_path?>',
        newestText: '',
        oldestText: '',

        popularText: '',
        sendText: 'Comment',

        editText: 'Modify',
        youText: '<?php echo $name?>',
        highlightColor: 'green',
        enableReplying: false,
        enableUpvoting: false,
        postCommentOnEnter: true,
        roundProfilePictures:true,
           readOnly: <?php echo $read_only;?>, //vip
        getComments: function(success, error) {
            var commentsArray = [{
                id: 1,
                created: '2015-10-01',
                content: 'Lorem ipsum dolort sit amet',
                fullname: 'Simon Powell',
                upvote_count: 2,
                user_has_upvoted: false
            }];
            success(commentsArray);
        },
        postComment: function(commentJSON, success, error) {
            commentJSON.id=<?php echo $id;?>; //user id
            commentJSON.parent=<?php echo $article_id ;?>; //post id

            $.ajax({
                type: 'post',
                url: '/article/articel-post-comment',
                data: commentJSON,
                success: function(comment) {

                    var parsed = JSON.parse(comment);
                    success(parsed)

                }

            });
        }
    });
</script>