<?php


echo '<div class="site-slider"> ';//top six countries
        echo '<ul class="bxslider">';
        foreach($this->countries as $key => $value)
        {
            echo'<li>';
            
            echo "<a href='/country/list-cities/id/".$value['id']."'><img style='width:1600px; height:660px;' src='".$value['image_path']. "'"."alt='slider image 1'></a>";
                echo '<div class="container">';
                   echo ' <div class="row">';
                        echo '<div class="col-md-12 text-right">';
                           echo ' <div class="slider-caption">';
                               echo ' <h2>'.$value['name'].'</h2>';
                           echo  '</div>';
                        echo '</div>';
                    echo '</div>';
                echo '</div>';
            echo '</li>';
        }
            
                
            
            
            
            
       echo  '</ul> <!-- /.bxslider -->';
        echo'<div class="bx-thumbnail-wrapper">';
           echo '<div class="container">';
                echo '<div class="row">';
                    echo '<div class="col-md-12">';
                        echo '<div id="bx-pager">';
                            $i=0;
                            foreach($this->countries as $key => $value)
                             { 
                            echo "<a data-slide-index='".$i."'"." href=''><img style='width:170px; height:80px;' src='".$value['image_path']."'"." alt='image 1'/></a>";
                               
                              $i++;
                             }
                            
                        echo'</div>';
                   echo '</div>';
                echo '</div>';
            echo'</div>';
        echo'</div>';
    echo'</div> <!-- /.site-slider -->';


    echo '<div id="products" class="content-section">';
        echo '<div class="container">';
            echo'<div class="row">';
                echo '<div class="col-md-12 text-center">';
                    echo '<h1 class="section-title">Cities</h1>';
                echo '</div> <!-- /.col-md-12 -->';
            echo '</div> <!-- /.row -->';
            
            echo '<div class="row">';
            foreach($this->cities as $key => $value)
            {

              echo'<div class="col-md-4 col-sm-6">';
                    echo'<div class="product-item">';
                        echo'<div class="item-thumb">';
                            
                            echo'<div class="overlay">';
                                echo'<div class="overlay-inner">';
                                   echo' <a href="/city/list-experience/city_id/'.$value['id'].'" class="view-detail"></a>';
                                echo'</div>';
                            echo'</div> <!-- /.overlay -->';

                            echo"<img style='width:400px; height:400px;' src='".$value['imag_path']."'". "alt=''>";

                        echo'</div> <!-- /.item-thumb -->';
                    echo'</div> <!-- /.product-item -->';
                echo'</div> <!-- /.col-md-4-->';

            }
                
                
                
                
                echo '</div><!-- row-->';
                
                
           echo '</div> <!-- /.row -->';
           
        echo'</div> <!-- /.container -->';
    echo'</div> <!-- /#products -->';
?>

