<head>
 <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet">
    <meta charset=utf-8>
    <link rel="stylesheet" href="/resources/css/bootstrap.min.css">
    <link rel="stylesheet" href="/resources/css/normalize.min.css">
    <link rel="stylesheet" href="/resources/css/font-awesome.min.css">
    <link rel="stylesheet" href="/resources/css/animate.css">
    <link rel="stylesheet" href="/resources/css/templatemo_misc.css">
    <link rel="stylesheet" href="/resources/css/templatemo_style.css">
    <link rel="stylesheet" type="text/css" href="/resources/css/jquery-comments.css">


    <script src="/resources/js/vendor/jquery-1.10.1.min.js"></script>
    <script type="text/javascript" src="/resources/js/jquery-comments.js"></script>
    <script src="/resources/js/vendor/modernizr-2.6.2.min.js"></script>
</head>

<!-- Header Content-->
 <div id="front">
        <div class="site-header">
            <div class="container">
                <div class="row">

                    <div class="col-md-7 col-sm-6 col-xs-6">
                        <a href="#" class="toggle-menu"><i class="fa fa-bars"></i></a>
                        <div class="main-menu">
                            <ul>
                                <li class="dropdown" id="tt-blog">
        <a href="#!" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-target="#">Countries <span class="caret"></span><a>
        <ul class="dropdown-menu" role="menu">
          <li><a href="#!">Egypt</a></li>
          <li><a href="#!">Korea</a></li>
        </ul>
</li>
                                <li><button class="btn btn-default">SignUp</button></li>
                                <li><button class="btn btn-default">SignIn</button></li>
                                






                            </ul>
                        </div> <!-- /.main-menu -->
                    </div> <!-- /.col-md-7 -->
                </div> <!-- /.row -->
                
            </div> <!-- /.container -->
        </div> <!-- /.site-header -->
    </div> <!-- /#front -->


<!--End Of Header Content -->
 <br><br>
<?php echo $this->layout()->content; ?>
<!-- Foter Content-->
<div class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-6">
                    <span id="copyright">
                    	Copyright &copy; 2014 <a href="#">Company Name</a>
                    	
                        
                      
                    </span>

            </div> <!-- /.col-md-6 -->
                <div class="col-md-4 col-sm-6">
                    <ul class="social">
                        <li><a href="#" class="fa fa-facebook"></a></li>
                        <li><a href="#" class="fa fa-twitter"></a></li>
                    </ul>
                </div> <!-- /.col-md-6 -->
            </div> <!-- /.row -->
        </div> <!-- /.container -->
    </div> <!-- /.site-footer -->

<!-- End Of Foter Content-->



    <script src="/resources/js/jquery.easing-1.3.js"></script>
    <script src="/resources/js/bootstrap.js"></script>
    <script src="/resources/js/plugins.js"></script>
    <script src="/resources/js/main.js"></script>
