<div style="height:100px;"></div>
<div id="view-content">

	<h3 align="center" > Hotel Reservation </h3>
	<table class='table'>
		<thead>
		<tr>
			<th>ID</th><th>Hotel Name</th><th>From</th><th>To</th><th>Number of adults</th>
		</tr>
		</thead>
		<?php
		foreach($this->hotelByUserId as $key => $value)
		{
			echo "<tr>".
				"<td>" . $value['id'] . "</td>" .
				"<td>" . $value['name'] . "</td>" .
				"<td>" . $value['time_from'] . "</td>" .
				"<td>" . $value['time_to'] . "</td>" .
				"<td>" . $value['number_of_adults'] . "</td>" .
				"</tr>";
		}
		?>

	</table>
</div>

