<div style="height:120px;"></div>
<div id="view-content">
	<?php
	$user_id=$this->user_id;
	echo "<h3 align='center'> Posts <a href='/user/addpost/user_id/".$user_id."'>Add Post</a></h3>"
	?>

	<table class='table'>
		<thead>
		<tr>
			<th>ID</th><th>Post Title</th><th>Edit</th><th>Delete</th>
		</tr>
		</thead>
		<?php
		foreach($this->postByUserId as $key => $value)
		{
			echo "<tr>".
				"<td>" . $value['id'] . "</td>" .
				"<td>" . $value['title'] . "</td>" .
				"<td><a class='btn btn-success' href='/user/editpost/pid/".$value['id']."/user_id/".$user_id."'>Edit</a></td>".
				"<td><a class='btn btn-danger' href='/user/deletepost/pid/".$value['id']."/user_id/".$user_id."'>Delete</a></td>".
				"</tr>";
		}
		?>

	</table>

</div>