<br> <br> <br> <br> <br>
<?php 

  echo $this->dataUser;
  

 

	  
 


?>
<h2>Car Rental :</h2>
<table class="table table-striped table-bordered table-hover">

<tr> 
   <th>pick up location</th>
   <th>Date from</th>
   <th>Date to</th>
   <th>Time from </th>
   <th>Time to </th>

</tr>

<?php
foreach($this->datacar as $key => $value)
{
echo "<tr>".
"<td>" . $value['pick_up_location']
. "</td>" .
"<td>" . $value['Date_from'] . "</td>" .
"<td>" . $value['Date_to'] . "</td>" .
"<td>" . $value['Time_from'] . "</td>" .
"<td>" . $value['Time_to'] . "</td>" .
"</tr>";
}
?>
</table>


<h2>Hotel Reserver :</h2>
<table class="table table-striped table-bordered table-hover">

<tr> 
   <th>name</th>
   <th>Time From</th>
   <th>Time To</th>
   <th>Number Of Adults</th>
   

</tr>

<?php

foreach($this->dathotel as $key => $value)
{
echo "<tr>".

"<td>" . $value['name'] . "</td>" .
"<td>" . $value['time_from'] . "</td>" .
"<td>" . $value['time_to'] . "</td>" .
"<td>" . $value['number_of_adults'] . "</td>" .
"</tr>";
}
?>
</table>

