<br /><br /><br />
<div id="view-content">
	<h3 align="center" > Cities <a href='addcity'>Add City</a></h3>
	<table class='table'>
		<thead>
		<tr>
			<th>ID</th><th>City Name</th><th>Edit</th><th>Delete</th>
		</tr>
		</thead>
		<?php
		foreach($this->all_cities as $key => $value)
		{
			echo "<tr>".
				"<td>" . $value['id'] . "</td>" .
				"<td>" . $value['name'] . "</td>" .
				"<td><a class='btn btn-success' href='editcity/cid/".$value['id']."'>Edit</a></td>".
				"<td><a class='btn btn-danger' href='deletecity/cid/".$value['id']."'>Delete</a></td>".
				"</tr>";
		}
		?>

	</table>

</div>

