<br /><br /><br />
<div id="view-content">

	<h3 align="center" > Countries <a href='addcountry'>Add Country</a></h3>
	<table class='table'>
		<thead>
		<tr>
			<th>ID</th><th>Country Name</th><th>Edit</th><th>Delete</th>
		</tr>
		</thead>
		<?php
		foreach($this->all_countries as $key => $value)
		{
			echo "<tr>".
				"<td>" . $value['id'] . "</td>" .
				"<td>" . $value['name'] . "</td>" .
				"<td><a class='btn btn-success' href='editcountry/cid/".$value['id']."'>Edit</a></td>".
				"<td><a class='btn btn-danger' href='deletecountry/cid/".$value['id']."'>Delete</a></td>".
				"</tr>";
		}
		?>

	</table>
</div>

