<div style="height:150px;"></div>
<div id="view-content">

	<h3 align="center" > Hotels <a href='addhotel'>Add Hotel </a></h3>
	<table class='table'>
		<thead>
		<tr>
			<th>ID</th><th>Hotel Name</th><th>Edit</th><th>Delete</th>
		</tr>
		</thead>
		<?php
		foreach($this->all_hotels as $key => $value)
		{
			echo "<tr>".
				"<td>" . $value['id'] . "</td>" .
				"<td>" . $value['name'] . "</td>" .
				"<td><a class='btn btn-success' href='edithotel/hid/".$value['id']."'>Edit</a></td>".
				"<td><a class='btn btn-danger' href='deletehotel/hid/".$value['id']."'>Delete</a></td>".
				"</tr>";
		}
		?>

	</table>
</div>

