<div style="height:100px;"></div>
<div id="view-content">


	<h3 align="center" > Locations <a href='addlocation'>Add Location</a></h3>
	<table class='table'>
		<thead>
		<tr>
			<th>ID</th><th>Location Name</th><th>Edit</th><th>Delete</th>
		</tr>
		</thead>
		<?php
		foreach($this->all_locations as $key => $value)
		{
			echo "<tr>".
				"<td>" . $value['id'] . "</td>" .
				"<td>" . $value['name'] . "</td>" .
				"<td><a class='btn btn-success' href='editlocation/lid/".$value['id']."'>Edit</a></td>".
				"<td><a class='btn btn-danger' href='deletelocation/lid/".$value['id']."'>Delete</a></td>".
				"</tr>";
		}
		?>

	</table>
</div>
