<br /><br /><br />
<div id="view-content">
	<h3 align="center" > Users </h3>
	<table class='table'>
		<thead>
		<tr>
			<th>ID</th><th>City Name</th><th>BLock</th><th>Delete</th>
		</tr>
		</thead>
		<?php
		foreach($this->all_users as $key => $value)
		{

			echo "<tr>".
				"<td>" . $value['id'] . "</td>" .
				"<td>" . $value['name'] . "</td>" ;
				if($value['is_active']==1)
				{
					echo"<td><a class='btn btn-danger' href='blockuser/uid/".$value['id']."'>Block</a></td>";
				}
				else{
					echo"<td><a class='btn btn-success' href='unblockuser/uid/".$value['id']."'>UnBlock</a></td>";
				}
			echo"<td><a class='btn btn-danger' href='deleteuser/uid/".$value['id']."'>Delete</a></td>".

				"</tr>";
		}
		?>

	</table>
</div>