
<br /><br />
<div class="container" >
	<div style="height: 50px;"></div>

	<table class="table table-striped table-bordered table-hover">
		<h1>Mange Site:</h1>

		<?php


echo  $this->home ;
		?>
		<tr>
				<td> <a class='btn btn-info' href='allcities'> Mange Cities </a> </td>
				</tr>

		<tr>

			<td> <a class='btn btn-info' href='allcountries'> Mange Countries </a> </td>

			</tr>
		<tr>
			<td> <a class='btn btn-info' href='alllocations'> Mange Location </a> </td>

			</tr>
		<tr>
			<td> <a class='btn btn-info' href='allhotels'> Mange Hotels </a> </td>

		</tr>
		<tr>
			<td> <a class='btn btn-info' href='allusers'> Mange Users </a> </td>

		</tr>
	</table>

			 <a class='btn btn-primary' href='logout'> Logout </a>


</div>

